dist: xenial
language: python
python:
    - "3.6"
    - "3.6-dev"
    - "3.7"
    - "3.7-dev"
    - "3.8-dev"
install:
    - pip install .
script:
    - python setup.py test
addons:
    chrome: stable
sudo: required
after_success:
  - bash <(curl -s https://codecov.io/bash)
