dist: trusty
language: python
python:
    - "3.4"
    - "3.5"
    - "3.6"
    - "pypy3.5"
install:
    - pip install .
script:
    - pytest --cov=crocoite crocoite
addons:
    chrome: stable
sudo: required
